version: '3.6'
services:
  node:
    image: node:9.11.1-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ~/.npm:/root/.npm
      - node_modules:/app/node_modules

volumes:
  node_modules:
